import { StyleSheet } from "react-native";

export const AyudaEstilos = StyleSheet.create({
  contenedor: { flex: 1, backgroundColor: "#f9fafb" },
  encabezado: {
    paddingTop: 60,
    paddingHorizontal: 20,
    paddingBottom: 30,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    marginBottom: 20,
  },
  tituloEncabezado: { fontSize: 24, fontWeight: "bold", color: "#fff" },
  subtituloEncabezado: {
    fontSize: 14,
    color: "rgba(255,255,255,0.8)",
    marginTop: 5,
  },
  seccion: { padding: 20 },
  tituloSeccion: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#1f2937",
    marginBottom: 15,
    marginLeft: 5,
  },
  itemPregunta: {
    backgroundColor: "#fff",
    padding: 20,
    borderRadius: 16,
    marginBottom: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.03,
    shadowRadius: 5,
    elevation: 1,
  },
  textoPregunta: { fontSize: 15, color: "#333", flex: 1 },
  botonContacto: {
    backgroundColor: "#fff",
    marginHorizontal: 20,
    marginVertical: 10,
    padding: 20,
    borderRadius: 20,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#C21833",
    shadowOpacity: 0.1,
    shadowRadius: 10,
    elevation: 2,
  },
  textoContacto: {
    marginLeft: 15,
    fontSize: 16,
    color: "#BF1A2F",
    fontWeight: "bold",
  },
});
