import { StyleSheet } from "react-native";

export const DireccionesEstilos = StyleSheet.create({
  contenedor: { flex: 1, backgroundColor: "#f9fafb" },
  encabezado: {
    paddingTop: 60,
    paddingHorizontal: 20,
    paddingBottom: 30,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    marginBottom: 20,
  },
  tituloEncabezado: { fontSize: 24, fontWeight: "bold", color: "#fff" },
  lista: { padding: 20 },
  tarjeta: {
    backgroundColor: "#fff",
    padding: 20,
    borderRadius: 20,
    marginBottom: 15,
    shadowColor: "#C21833",
    shadowOpacity: 0.08,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  infoDireccion: { flex: 1, paddingRight: 10 },
  tituloDireccion: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#1f2937",
    marginBottom: 5,
  },
  textoDireccion: { fontSize: 14, color: "#6b7280" },
  iconoDireccion: {
    width: 40,
    height: 40,
    borderRadius: 12,
    backgroundColor: "#ffe4e6",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 15,
  },
  botonAgregar: {
    backgroundColor: "#C21833",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 18,
    borderRadius: 24,
    margin: 20,
    shadowColor: "#C21833",
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 5,
  },
  textoBoton: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
    marginLeft: 10,
  },
});
