import { StyleSheet } from "react-native";

export const MetodosPagoEstilos = StyleSheet.create({
  contenedor: { flex: 1, backgroundColor: "#f9fafb" },
  encabezado: {
    paddingTop: 60,
    paddingHorizontal: 20,
    paddingBottom: 30,
    borderBottomLeftRadius: 30,
    borderBottomRightRadius: 30,
    marginBottom: 20,
  },
  tituloEncabezado: { fontSize: 24, fontWeight: "bold", color: "#fff" },
  lista: { padding: 20 },
  tarjeta: {
    backgroundColor: "#fff",
    padding: 25,
    borderRadius: 24,
    marginBottom: 20,
    shadowColor: "#C21833",
    shadowOpacity: 0.1,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
    elevation: 4,
    position: "relative",
    overflow: "hidden",
  },
  fondoTarjeta: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    opacity: 0.1,
  },
  filaTarjeta: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  numeroTarjeta: {
    fontSize: 20,
    letterSpacing: 2,
    color: "#333",
    fontWeight: "600",
    marginBottom: 10,
  },
  infoTarjeta: { flexDirection: "row", justifyContent: "space-between" },
  etiqueta: { fontSize: 12, color: "#999", marginBottom: 2 },
  valor: { fontSize: 14, fontWeight: "bold", color: "#333" },
  botonAgregar: {
    marginTop: 20,
    marginHorizontal: 20,
    borderWidth: 2,
    borderColor: "#e5e7eb",
    borderStyle: "dashed",
    borderRadius: 20,
    padding: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#fff",
  },
  textoAgregar: { color: "#6b7280", fontWeight: "600", marginTop: 5 },
});
